### PR TITLE
Some rework of WearActivity.java

### PR DESCRIPTION
**Pull request by jamorham**
I think this works and is an improvement but you should test it to verify my findings.

It needs root installed on the watch. I installed a wear compatible super-su binary via twrp from here:

http://forum.xda-developers.com/attachment.php?attachmentid=3342605&d=1433157678

### CODE REVIEW

**Comment by jamorham** [comment]
I've reworked this again after I found some times NFC got left on. I have it integrating with xDrip+ now so I think I will submit an updated PR with all the bits needed as soon as I've tidied that up and tested it a little more.

**Comment by dabear** [comment]
why does it require root?

**Comment by jamorham** [comment]
Because the watch activity is doing things like turning off the nfc service, adjusting the cpu clock speed and being able to disable the kernel touchscreen driver to ensure no screen presses occur.

As the watch is already being flashed with a custom kernel I didn't think the root requirement would be a big ask to give maximum flexibility for what we can do within the watch component.

**Comment by jamorham** [comment]
Have a look at https://github.com/pimpimmi/LibreAlarm/pull/18 instead now as it supersedes this.

**Pull request closed without merging**
